name: Geography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36217561457306147
title: Hello Geography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69432520-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#000000'
    - '#a5a5a5'
    - '#db5332'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
